// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  app.Door = (function(_super) {
    __extends(Door, _super);

    Door.include(new app.Bombblowable());

    function Door(envCtx, x, y) {
      this.envCtx = envCtx;
      this.x = x;
      this.y = y;
      Door.__super__.constructor.call(this, 'door');
      this.eventAggregator.subscribe('robbo-moving', ((function(_this) {
        return function() {
          return _this.openDoor();
        };
      })(this)), this, (function(_this) {
        return function(x, y) {
          return x === _this.x && y === _this.y;
        };
      })(this));
    }

    Door.prototype.openDoor = function() {
      var robbo;
      robbo = this.envCtx.getRobbo();
      if (robbo.keys > 0) {
        this.eventAggregator.publish('key-used');
        this.envCtx.sound('door');
        return this.envCtx.delay(100, (function(_this) {
          return function() {
            _this.eventAggregator.unsubscribe(_this);
            return _this.envCtx.setObjAt(_this.x, _this.y, null);
          };
        })(this));
      }
    };

    return Door;

  })(app.Object);

}).call(this);
