// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  app.KeyboardWatcher = (function() {
    function KeyboardWatcher(eventAggregator) {
      this.eventAggregator = eventAggregator;
      $(document).keydown((function(_this) {
        return function(e, ee) {
          var direction, _ref1;
          if ((37 <= (_ref1 = e.keyCode) && _ref1 <= 40)) {
            switch (e.keyCode) {
              case 37:
                direction = 'left';
                break;
              case 38:
                direction = 'up';
                break;
              case 39:
                direction = 'right';
                break;
              case 40:
                direction = 'down';
            }
            _this.eventAggregator.publish("arrow-down", {
              keyCode: e.keyCode,
              direction: direction,
              ctrl: e.ctrlKey,
              shift: e.shiftKey
            });
          }
          return _this.eventAggregator.publish("key-down", {
            keyChar: e.which,
            keyCode: e.keyCode,
            ctrl: e.ctrlKey,
            shift: e.shiftKey
          });
        };
      })(this));
      $(document).keyup((function(_this) {
        return function(e, ee) {
          return _this.eventAggregator.publish("key-up", {
            keyChar: String.fromCharCode(e.keyCode),
            keyCode: e.keyCode,
            ctrl: e.ctrlKey,
            shift: e.shiftKey
          });
        };
      })(this));
      $(document).keypress((function(_this) {
        return function(e, ee) {
          return _this.eventAggregator.publish("key-press", {
            keyChar: String.fromCharCode(e.keyCode),
            keyCode: e.keyCode,
            ctrl: e.ctrlKey,
            shift: e.shiftKey
          });
        };
      })(this));
    }

    return KeyboardWatcher;

  })();

}).call(this);
