// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  app.RestartLevelWatcher = (function() {
    function RestartLevelWatcher(envCtx, eventAggregator) {
      this.envCtx = envCtx;
      this.eventAggregator = eventAggregator;
      this.eventAggregator.subscribe('key-press', ((function(_this) {
        return function(args) {
          return _this.restartLevel();
        };
      })(this)), (function(_this) {
        return function(args) {
          return args.keyChar = "r" && args.shiftKey;
        };
      })(this));
    }

    RestartLevelWatcher.prototype.restartLevel = function() {
      var robbo;
      robbo = this.envCtx.getRobbo();
      return robbo.blowUp();
    };

    return RestartLevelWatcher;

  })();

}).call(this);
