// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  app.ColorTranslation = [
    {
      from: [0, 0, 0, 0],
      to: [0, 0, 0, 0]
    }, {
      from: [162, 114, 64, 255],
      to: [162, 114, 64, 255]
    }, {
      from: [28, 39, 131, 255],
      to: [28, 39, 129, 255]
    }, {
      from: [16, 16, 16, 255],
      to: [16, 16, 16, 255]
    }, {
      from: [152, 152, 152, 255],
      to: [152, 152, 152, 255]
    }, {
      from: [255, 255, 255, 255],
      to: [0, 0, 0, 0]
    }
  ];

  app.ColorManager = (function() {
    function ColorManager(canvas, background, transparent, colors) {
      var color, i, _i, _len;
      app.ColorTranslation[0].to = transparent;
      for (i = _i = 0, _len = colors.length; _i < _len; i = ++_i) {
        color = colors[i];
        app.ColorTranslation[i + 1].to = color;
      }
      if (canvas != null) {
        canvas.css('background-color', "rgba(" + background[0] + "," + background[1] + "," + background[2] + "," + background[3] + ")");
      }
    }

    return ColorManager;

  })();

}).call(this);
