// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  app.GameLoader = (function() {
    GameLoader.loadGamesConfig = function() {
      var game, gamesList, i, planet, planetsList, _i, _j, _len, _len1, _ref1, _ref2;
      gamesList = $('.games');
      planetsList = $('.planets');
      _ref1 = app.Universe.Games;
      for (i = _i = 0, _len = _ref1.length; _i < _len; i = ++_i) {
        game = _ref1[i];
        gamesList.append($('<option></option>').attr('value', i).text(game.Name));
        _ref2 = game.Planets;
        for (i = _j = 0, _len1 = _ref2.length; _j < _len1; i = ++_j) {
          planet = _ref2[i];
          planetsList.append($('<option></option>').attr('value', i).text(planet.Name));
        }
        return;
      }
    };

    GameLoader.currentGame = function() {
      return $('.games').val();
    };

    GameLoader.currentPlanet = function() {
      return $('.planets').val();
    };

    function GameLoader() {
      this.gamesList = $('.games');
      this.planetsList = $('.planets');
      app.GameLoader.loadGamesConfig();
      $('button.play').click((function(_this) {
        return function() {
          return _this.startGame();
        };
      })(this));
      this.setRequestedPlanet();
    }

    GameLoader.prototype.startGame = function() {
      var game;
      game = app.Universe.Games[this.gamesList.val()];
      game = new app.Game($('.game-board'), game, this.planetsList);
      return new app.ColorManager($('.game-board canvas'), function() {
        return game.redraw();
      });
    };

    GameLoader.prototype.setRequestedPlanet = function() {
      var vars;
      vars = this.getParams();
      if ((vars["game"] != null)) {
        this.gamesList.val(vars["game"]);
      }
      if ((vars["planet"] != null)) {
        this.planetsList.val(vars["planet"]);
        return this.startGame();
      }
    };

    GameLoader.prototype.getParams = function() {
      var key, params, query, raw_vars, v, val, _i, _len, _ref1;
      query = window.location.search.substring(1);
      raw_vars = query.split("&");
      params = {};
      for (_i = 0, _len = raw_vars.length; _i < _len; _i++) {
        v = raw_vars[_i];
        _ref1 = v.split("="), key = _ref1[0], val = _ref1[1];
        params[key] = decodeURIComponent(val);
      }
      return params;
    };

    return GameLoader;

  })();

}).call(this);

//# sourceMappingURL=GameLoader.map
