// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  app.LevelManger = (function() {
    function LevelManger(gameBoard, game, planetsList, currentLevel) {
      this.gameBoard = gameBoard;
      this.game = game;
      this.planetsList = planetsList;
      this.currentLevel = currentLevel;
      this.lives = this.game.startingNumberOfLives;
    }

    LevelManger.prototype.setupCanvas = function() {
      this.canvas = $('<canvas></canvas>');
      this.gameBoard.html('');
      this.gameBoard.append(this.canvas);
      return this.canvasContext2D = this.canvas.get(0).getContext('2d');
    };

    LevelManger.prototype.setupLevel = function(planet) {
      this.setupCanvas();
      this.eventAggregator = new app.EventAggregator();
      this.drawingCtx = new app.DrawingContext(this.canvasContext2D);
      this.keyboardWatcher = new app.KeyboardWatcher(this.eventAggregator);
      this.timer = new app.TimeDelayedMethodCall;
      this.envCtx = new app.EnvironmentContext(this.eventAggregator, this.drawingCtx, this.timer);
      this.mapLoader = new app.MapLoader(this.envCtx, this.canvas);
      this.effectManager = new app.MapEffects(this.canvas, this.envCtx);
      this.setupWatchers();
      this.subscribeToEvents();
      new app.ColorManager($('.game-board canvas'), planet.background, planet.transparent, planet.colors);
      this.envCtx.eventAggregator.publish('starting-number-of-bolts', planet.boltsToBeCollected);
      this.envCtx.eventAggregator.publish('load-level', planet);
      return this.watchCoordinates();
    };

    LevelManger.prototype.setupWatchers = function() {
      this.scrollWatcher = new app.ScrollWatcher(this.envCtx, this.eventAggregator, this.canvas);
      this.boltWatcher = new app.BoltWatcher(this.eventAggregator);
      this.keyWatcher = new app.KeyWatcher(this.eventAggregator);
      this.liveWatcher = new app.LiveWatcher(this.lives, this.eventAggregator);
      this.ammoWatcher = new app.AmmoWatcher(this.eventAggregator);
      return this.restartLevelWatcher = new app.RestartLevelWatcher(this.envCtx, this.eventAggregator);
    };

    LevelManger.prototype.subscribeToEvents = function() {
      this.envCtx.eventAggregator.subscribe('robbo-destroyed', ((function(_this) {
        return function() {
          return _this.onRobboDestroyed();
        };
      })(this)));
      this.envCtx.eventAggregator.subscribe('level-loaded', ((function(_this) {
        return function() {
          return _this.onLevelStarts();
        };
      })(this)));
      this.envCtx.eventAggregator.subscribe('level-up', ((function(_this) {
        return function() {
          return _this.onLevelUp();
        };
      })(this)));
      return this.eventAggregator.subscribe('live-collected', ((function(_this) {
        return function() {
          return _this.lives++;
        };
      })(this)));
    };

    LevelManger.prototype.startGame = function() {
      return this.setupLevel(this.game.planets.single((function(_this) {
        return function(p) {
          return p.index.toString() === _this.currentLevel.toString();
        };
      })(this)));
    };

    LevelManger.prototype.onLevelUp = function() {
      var planet;
      this.envCtx.eventAggregator.unsubscribeAll();
      this.timer.resetToken();
      this.currentLevel++;
      planet = this.game.planets.single((function(_this) {
        return function(p) {
          return p.index.toString() === _this.currentLevel.toString();
        };
      })(this));
      if (planet == null) {
        $('.screen').hide();
        $('.game-finished-screen').show();
        return;
      }
      return this.setupLevel(planet);
    };

    LevelManger.prototype.watchCoordinates = function() {
      return this.canvas.mousemove((function(_this) {
        return function(e) {
          var x, y;
          x = Math.floor((e.pageX - _this.canvas.offset().left) / 32.0);
          y = Math.floor((e.pageY - _this.canvas.offset().top) / 32.0);
          if (x < 10) {
            x = '0' + x;
          }
          if (y < 10) {
            y = '0' + y;
          }
          return $(app.Predef.Selectors.Coordinates).text("[" + x + "," + y + "]");
        };
      })(this));
    };

    LevelManger.prototype.onLevelStarts = function() {
      this.envCtx.eventAggregator.publish('level-started');
      this.planetsList.val(this.currentLevel - 1);
      return this.envCtx.sound('level-starts');
    };

    LevelManger.prototype.onRobboDestroyed = function() {
      var explosionCallback;
      this.lives--;
      explosionCallback = (function(_this) {
        return function() {
          var obj, smoke, x, y, _i, _j, _ref1, _ref2;
          _this.envCtx.sound('explosion');
          for (y = _i = 0, _ref1 = _this.envCtx.height - 1; 0 <= _ref1 ? _i <= _ref1 : _i >= _ref1; y = 0 <= _ref1 ? ++_i : --_i) {
            for (x = _j = 0, _ref2 = _this.envCtx.width - 1; 0 <= _ref2 ? _j <= _ref2 : _j >= _ref2; x = 0 <= _ref2 ? ++_j : --_j) {
              obj = _this.envCtx.getObjAt(x, y);
              if ((obj != null) && _this.envCtx.getObjName(obj) !== 'Smoke' && ((typeof obj.canBlowUp === "function" ? obj.canBlowUp() : void 0) || (typeof obj.canBombBlowUp === "function" ? obj.canBombBlowUp() : void 0))) {
                obj.isActive = false;
                smoke = new app.Smoke(_this.envCtx, obj.x, obj.y);
                _this.envCtx.putObj(smoke);
                _this.envCtx.eventAggregator.unsubscribe(obj);
                _this.envCtx.unregisterRandomCalls(obj);
                smoke.init();
              }
            }
          }
          return setTimeout((function() {
            if (_this.lives > 0) {
              return _this.envCtx.eventAggregator.publish('restart-level', _this.game.planets[_this.currentLevel - 1]);
            } else {
              $('.game-chrome').hide();
              return $('.game-over-screen').show();
            }
          }), 2000);
        };
      })(this);
      return setTimeout(explosionCallback, 700);
    };

    return LevelManger;

  })();

}).call(this);
