// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  app.RobboGame = (function() {
    function RobboGame() {
      var interval;
      interval = setInterval(this.setupLogoSpectrumAnimation, 1800);
      $('.start-game').click((function(_this) {
        return function() {
          clearInterval(interval);
          $('.game-logo').stop().removeClass('.color-animated').css('color', 'green');
          $('.screen').hide();
          $('.game-chrome').show();
          return new app.GameLoader();
        };
      })(this));
    }

    RobboGame.prototype.setupLogoSpectrumAnimation = function() {
      var hue;
      $('.color-animated').stop();
      hue = 'rgb(' + (Math.floor(Math.random() * 256)) + ',' + (Math.floor(Math.random() * 256)) + ',' + (Math.floor(Math.random() * 256)) + ')';
      $('.color-animated').animate({
        color: hue
      }, 1500);
    };

    return RobboGame;

  })();

}).call(this);
