// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  app.RobboGame = (function() {
    function RobboGame() {
      $('button.start-game, button.play-again').click((function(_this) {
        return function() {
          return _this.startGame();
        };
      })(this));
      $('button.back-home').click((function(_this) {
        return function() {
          return _this.backHome();
        };
      })(this));
    }

    RobboGame.prototype.backHome = function() {
      $('.screen').hide();
      return $('.start-screen').show();
    };

    RobboGame.prototype.startGame = function() {
      this.currentGame = null;
      $('.screen').hide();
      $('.game-chrome').show();
      return this.currentGame = new app.GameLoader();
    };

    RobboGame.prototype.setupLogoSpectrumAnimation = function() {
      var hue;
      $('.color-animated').stop();
      hue = 'rgb(' + (Math.floor(Math.random() * 256)) + ',' + (Math.floor(Math.random() * 256)) + ',' + (Math.floor(Math.random() * 256)) + ')';
      $('.color-animated').animate({
        color: hue
      }, 1500);
    };

    return RobboGame;

  })();

}).call(this);
