// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  module("MapStruct");

  test("properly parse map to structure", function() {
    var mapStruct;
    mapStruct = new app.MapStruct("T10_.._.._.._.._.._..\n_.._.._.._.._.._.._..\n_.._.._.._.._.._.._..\n_.._.._..T21_.._.._..\n_..T38_.._.._.._.._..");
    equal(7, mapStruct.width(), 'correct width');
    return equal(5, mapStruct.height(), 'correct height');
  });

  test("properly parse map to structure when width and height even", function() {
    var mapStruct;
    mapStruct = new app.MapStruct("T10_.._.._.._.._..\n_.._.._.._.._.._..\n_.._.._.._.._.._..\n_.._.._..T21_.._..");
    equal(6, mapStruct.width(), 'correct width');
    return equal(4, mapStruct.height(), 'correct height');
  });

  test("properly parse map without empty line at the begining", function() {
    var mapStruct;
    mapStruct = new app.MapStruct("T10_.._.._.._.._..\n_.._.._.._.._.._..\n_.._.._.._.._.._..\n_.._.._..T21_.._..");
    equal(6, mapStruct.width(), 'correct width');
    return equal(4, mapStruct.height(), 'correct height');
  });

}).call(this);
