// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  Array.prototype.where = function(predicat) {
    var item, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = this.length; _i < _len; _i++) {
      item = this[_i];
      if (predicat(item)) {
        _results.push(item);
      }
    }
    return _results;
  };

  Array.prototype.single = function(predicat) {
    var item, items, _i, _len;
    items = [];
    for (_i = 0, _len = this.length; _i < _len; _i++) {
      item = this[_i];
      if (predicat(item)) {
        items.push(item);
      }
    }
    if (items.length === 1) {
      return items[0];
    }
    if (items.length === 0) {
      return null;
    }
    throw "Many items for given predicat";
  };

  Array.prototype.top = function(n) {
    return this.slice(0, n);
  };

  Array.prototype.skip = function(n) {
    return this.slice(n, this.length);
  };

  Array.prototype.firstIndexOf = function(predicat) {
    var e, i, _i, _len;
    for (i = _i = 0, _len = this.length; _i < _len; i = ++_i) {
      e = this[i];
      if (predicat(e)) {
        return i;
      }
    }
    return -1;
  };

  Array.prototype.any = function(predicat) {
    var item, items, _i, _len;
    if (predicat != null) {
      items = [];
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        item = this[_i];
        if (predicat(item)) {
          items.push(item);
        }
      }
      return items.length > 0;
    }
    return this.length > 0;
  };

  Array.prototype.contains = function(obj) {
    var item, _i, _len;
    for (_i = 0, _len = this.length; _i < _len; _i++) {
      item = this[_i];
      if (item === obj) {
        return true;
      }
    }
    return false;
  };

  Array.prototype.first = function() {
    return this[0];
  };

  Array.prototype.select = function(selector) {
    var item, ret, _i, _len;
    ret = [];
    for (_i = 0, _len = this.length; _i < _len; _i++) {
      item = this[_i];
      ret.push(selector(item));
    }
    return ret;
  };

  Array.prototype.last = function() {
    return this[this.length - 1];
  };

  Array.prototype.max = function(predicat) {
    var i, val, _i, _ref1, _results;
    if (this.length === 0) {
      return;
    }
    val = predicat(this[0]);
    if (this.length === 1) {
      return val;
    }
    _results = [];
    for (i = _i = 1, _ref1 = this.length - 1; 1 <= _ref1 ? _i <= _ref1 : _i >= _ref1; i = 1 <= _ref1 ? ++_i : --_i) {
      if (predicat(this[i]) > val) {
        _results.push(val = predicat(this[i]));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  app.Tools = {};

  app.Tools.getRand = function(x, y) {
    var i, _i;
    for (i = _i = 0; _i <= 113; i = ++_i) {
      Math.random();
    }
    return Math.floor((Math.random() * (y + 1)) + x);
  };

  app.Tools.getGaussRand = function(a, b, stdev) {
    var res;
    res = Math.round(app.Tools.rnd_snd() * stdev + ((a + b) / 2));
    if (res > b) {
      res = b;
    }
    if (res < a) {
      res = a;
    }
    return res;
  };

  app.Tools.rnd_snd = function() {
    return (Math.random() * 2 - 1) + (Math.random() * 2 - 1) + (Math.random() * 2 - 1);
  };

  String.prototype.rgbaToArray = function() {
    var num, nums, val, vals, _i, _len;
    val = this.toString();
    val = val.replace("rgba", "");
    val = val.replace(")", "");
    val = val.replace("(", "");
    vals = val.split(',');
    nums = [];
    for (_i = 0, _len = vals.length; _i < _len; _i++) {
      num = vals[_i];
      nums.push(parseFloat(num));
    }
    nums[3] = 255 * nums[3];
    return nums;
  };

  Array.prototype.toRgbaString = function() {
    return "rgba(" + this[0] + "," + this[1] + "," + this[2] + "," + this[3] + ")";
  };

}).call(this);
