// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  app.AssetLoader = (function() {
    function AssetLoader() {}

    AssetLoader.width = 32;

    AssetLoader.height = 32;

    AssetLoader.assetCanvas = null;

    AssetLoader.getAsset = function(name) {
      var asset, color, i, imgData, x, y, _i, _j;
      if (this.assetCanvas == null) {
        this.assetCanvas = $('.assetLoad')[0].getContext("2d");
      }
      asset = app.Assets[name];
      imgData = this.assetCanvas.createImageData(32, 32);
      for (y = _i = 0; _i <= 31; y = ++_i) {
        for (x = _j = 0; _j <= 31; x = ++_j) {
          color = app.ColorTranslation[asset[y][x]].to;
          i = y * 32 + x;
          imgData.data[i + 0] = color[0];
          imgData.data[i + 1] = color[1];
          imgData.data[i + 2] = color[2];
          imgData.data[i + 3] = color[3];
        }
      }
      return imgData;
    };

    AssetLoader.getPixel = function(data, n) {
      return [data.data[n * 4], data.data[n * 4 + 1], data.data[n * 4 + 2], data.data[n * 4 + 3]];
    };

    AssetLoader.compareColor = function(col1, col2) {
      return col1[0] === col2[0] && col1[1] === col2[1] && col1[2] === col2[2] && col1[3] === col2[3];
    };

    AssetLoader.setPixel = function(data, n, color) {
      var i, _i, _results;
      _results = [];
      for (i = _i = 0; _i <= 3; i = ++_i) {
        _results.push(data.data[n * 4 + i] = color[i]);
      }
      return _results;
    };

    return AssetLoader;

  })();

}).call(this);
