// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  app.ConstructorToolbar = (function() {
    function ConstructorToolbar(eventCtx) {
      this.eventCtx = eventCtx;
      this.setupToolbar();
      $(window).keydown((function(_this) {
        return function(event) {
          if (event.keyCode === 9) {
            return _this.rotateTools(event);
          }
        };
      })(this));
    }

    ConstructorToolbar.prototype.rotateTools = function(event) {
      var editor;
      editor = this;
      $('.tool').each(function(i, e) {
        var curr, imgs;
        imgs = $(this).find('img');
        if (imgs.size() === 1) {
          return;
        }
        curr = -1;
        imgs.each(function(j, img) {
          if ($(img).hasClass('curr')) {
            return curr = j;
          }
        });
        curr++;
        if (curr < 0) {
          curr = imgs.size() - 1;
        }
        if (curr === imgs.size()) {
          curr = 0;
        }
        imgs.removeClass('curr');
        $(imgs[curr]).addClass('curr');
        if ($(e).hasClass('selected')) {
          editor.selectedTool = $(imgs[curr]);
          editor.selectedToolIcon = $(imgs[curr]).data('tool-icon');
          return editor.selectedMapSign = $(imgs[curr]).data('map');
        }
      });
      this.eventCtx.publish('current-tool-changed');
      event.preventDefault();
      return false;
    };

    ConstructorToolbar.prototype.setupToolbar = function() {
      return $('.tool').click((function(_this) {
        return function(e, item) {
          $('.tool').removeClass('selected');
          $(e.target).parent().addClass('selected');
          _this.selectedTool = $(e.target);
          _this.selectedMapSign = $(e.target).data('map');
          return _this.selectedToolIcon = _this.selectedTool.data('tool-icon');
        };
      })(this));
    };

    return ConstructorToolbar;

  })();

}).call(this);
