// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  app.MapProcessing = (function() {
    function MapProcessing() {}

    MapProcessing.prototype.initTeleportNetwork = function(map) {
      var mapStruct, num, nums, _i, _len;
      mapStruct = new app.MapStruct(map);
      nums = this.getTeleportNums(mapStruct);
      for (_i = 0, _len = nums.length; _i < _len; _i++) {
        num = nums[_i];
        mapStruct = this.setTeleportSeq(mapStruct, num);
      }
      return mapStruct.toString();
    };

    MapProcessing.prototype.setTeleportSeq = function(mapStruct, num) {
      var seq;
      seq = 0;
      mapStruct.forEach(function(x, y, sign) {
        if ((sign != null) && sign.length === 3 && sign[0] === "T" && sign[1] === num.toString()) {
          sign = "T" + num + seq;
          mapStruct.set(x, y, sign);
          seq++;
        }
      });
      return mapStruct;
    };

    MapProcessing.prototype.getTeleportNums = function(mapStruct) {
      var nums;
      nums = [];
      mapStruct.forEach(function(x, y, sign) {
        if ((sign != null) && sign.length === 3 && sign[0] === "T") {
          if (!nums.contains(sign[1])) {
            return nums.push(sign[1]);
          }
        }
      });
      return nums;
    };

    MapProcessing.prototype.removeTeleportSeqNumbers = function(map) {
      return map.replace(/T(\d)./g, 'T$1.');
    };

    MapProcessing.prototype.removeEmptyLines = function(map) {
      var line, lines, resLines, _i, _len;
      lines = map.split('\n');
      resLines = [];
      for (_i = 0, _len = lines.length; _i < _len; _i++) {
        line = lines[_i];
        if (!(line === '' || line === "\n")) {
          resLines.push(line);
        }
      }
      return resLines.join('\n');
    };

    MapProcessing.prototype.preSaveProcessing = function(map) {
      map = this.initTeleportNetwork(map);
      map = this.removeEmptyLines(map);
      return map;
    };

    return MapProcessing;

  })();

}).call(this);
