// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  app.GameDesigner = (function() {
    function GameDesigner() {
      this.gameName = ko.observable();
      this.planetName = ko.observable();
      this.lives = ko.observable();
      this.bolts = ko.observable();
      this.width = ko.observable();
      this.height = ko.observable();
      this.optionsPanel = $('.options-panel');
      this.games = ko.observableArray();
      this.planets = ko.observableArray();
      this.selectedGame = ko.observable();
      this.selectedPlanet = ko.observable();
      this.selectedGameId = ko.observable(0);
      this.selectedPlanetId = ko.observable(0);
      this.selectedGameId.subscribe((function(_this) {
        return function() {
          _this.selectedGame = _this.games()[_this.selectedGameId()];
          _this.selectedPlanetId(0);
        };
      })(this));
      this.selectedPlanetId.subscribe((function(_this) {
        return function() {
          _this.selectedPlanet = _this.planets[_this.selectedPlanetId()];
          _this.load();
        };
      })(this));
      this.loadGames();
      this.loadPlanets();
      ko.applyBindings(this, $('.game-designer')[0]);
      $('.has-tooltip').tooltip();
    }

    GameDesigner.prototype.loadGames = function() {
      var game, i, _i, _len, _ref1;
      _ref1 = app.Universe.Games;
      for (i = _i = 0, _len = _ref1.length; _i < _len; i = ++_i) {
        game = _ref1[i];
        game.index = i;
        this.games.push(game);
      }
      this.selectedGameId(0);
      this.selectedGame(this.games[0]);
    };

    GameDesigner.prototype.loadPlanets = function() {
      var i, planet, _i, _len, _ref1;
      _ref1 = app.Universe.Games[this.selectedGameId()].Planets;
      for (i = _i = 0, _len = _ref1.length; _i < _len; i = ++_i) {
        planet = _ref1[i];
        planet.index = i;
        this.planets.push(planet);
      }
      this.selectedPlanetId(0);
      this.selectedPlanet(this.planets[0]);
    };

    GameDesigner.prototype.saveGame = function() {
      $('.save-game').text('Saving...');
      $.ajax({
        url: app.ConstructorConfig.serverAddress + "/api/robbo",
        data: app.Universe,
        type: "POST",
        success: function() {
          return setTimeout((function() {
            return $('.save-game').text('Save game');
          }), 200);
        }
      });
    };

    GameDesigner.prototype.newGame = function() {
      var name, planet;
      name = "Game " + this.games.length + 1;
      planet = this.createPlanet();
      planet.Name += " 1";
      app.Universe.Games.push({
        Name: name,
        StartingNumberOfLives: 9,
        Planets: [planet]
      });
      this.loadGames();
      this.load();
    };

    GameDesigner.prototype.removePlanet = function() {
      if (this.currentPlanetId() == null) {
        return;
      }
      if (!confirm("Are you sure you want remove current planet?")) {
        return;
      }
      return this.currentGame().Planets.splice(this.currentPlanetId(), 1);
    };

    GameDesigner.prototype.toggleRawMap = function() {
      if ($('.map').is(":visible")) {
        return $('.map').hide("blind");
      } else {
        return $('.map').show("blind");
      }
    };

    GameDesigner.prototype.removeGame = function() {
      if (this.currentGameId() === "0") {
        alert("You can't remove original game");
        return;
      }
      if (!confirm("Are you sure you want remove current game?")) {
        return;
      }
      return app.Universe.Games.splice(this.currentGameId(), 1);
    };

    GameDesigner.prototype.toggleOptions = function(x, e) {
      if (this.optionsPanel.is(':visible')) {
        return this.optionsPanel.hide('blind');
      } else {
        return this.optionsPanel.show('blind');
      }
    };

    GameDesigner.prototype.createPlanet = function() {
      var line, lines, planet, x, y, _i, _j;
      planet = {
        BoltsToBeCollected: 5,
        Name: "Planet",
        Map: ""
      };
      lines = [];
      for (x = _i = 0; _i <= 31; x = ++_i) {
        line = "";
        for (y = _j = 0; _j <= 16; y = ++_j) {
          line += "_..";
        }
        lines.push(line);
      }
      planet.Map = lines.join("\n");
      return planet;
    };

    GameDesigner.prototype.newPlanet = function() {
      var planet;
      planet = this.createPlanet();
      planet.Name += " " + (this.currentGame().Planets.length + 1);
      game.Planets.push(planet);
      app.Universe.Games[this.currentGameId()].Planets(push(planet));
      this.selectedPlanetId(game.Planets.length - 1);
      return this.load();
    };

    GameDesigner.prototype.testPlanet = function() {
      return window.open("robbo.html?game=" + (this.currentGameId()) + "&planet=" + (this.currentPlanetId()), "_blank");
    };

    GameDesigner.prototype.load = function() {
      this.width(app.MapLoader.getWidth(this.currentPlanet().Map));
      this.height(app.MapLoader.getHeight(this.currentPlanet().Map));
      this.planetName(this.currentPlanet().Name);
      this.gameName(this.currentGame().Name);
      this.bolts(this.currentPlanet().BoltsToBeCollected);
      return this.lives(this.currentGame().StartingNumberOfLives);
    };

    return GameDesigner;

  })();

  $(function() {
    return new app.GameDesigner();
  });

}).call(this);
