// Generated by CoffeeScript 1.7.1
(function() {
  var app, _ref;

  window.app = (_ref = window.app) != null ? _ref : {};

  app = window.app;

  module('Array tools');

  test("skip returns proper array", function() {
    var arr, skiped;
    arr = [1, 2, 3, 4, 5, 6, 7, 8];
    skiped = arr.skip(2);
    equal(skiped[0], 3);
    return equal(skiped.length, 6);
  });

}).call(this);
